/**
 *
 * @param Theme can be spread like {Colors, NavigationColors, Gutters, Layout, Common, ...args}
 * @return {*}
 */
export default function () {
  return {
    background: require('@/Assets/Images/background.png'),
    logo: require('@/Assets/Images/TOM.png'),
    home: require('@/Assets/Images/home.png'),
    homeFilled: require('@/Assets/Images/home_filled.png'),
    bell: require('@/Assets/Images/bell.png'),
    bellFilled: require('@/Assets/Images/bell_filled.png'),
    exchange: require('@/Assets/Images/exchange.png'),
    exchangeFilled: require('@/Assets/Images/exchange_filled.png'),
    favorite: require('@/Assets/Images/favourite.png'),
    favoriteFilled: require('@/Assets/Images/favourite_filled.png'),
    die: require('@/Assets/Images/die.png'),
    search: require('@/Assets/Images/search.png'),
    back: require('@/Assets/Images/back.png'),
    share: require('@/Assets/Images/share.png'),
    copy: require('@/Assets/Images/copy.png'),
    error: require('@/Assets/Images/error.png'),
    scanner: require('@/Assets/Images/scanner.png'),
    coin: require('@/Assets/Images/coin.png'),
    binance: require('@/Assets/Images/binance.png'),
    binanceHome: require('@/Assets/Images/home-binance.png'),
    polygon: require('@/Assets/Images/polygon.png'),
    polygonHome: require('@/Assets/Images/home-polygon.png'),
    solana: require('@/Assets/Images/solana.png'),
    solanaHome: require('@/Assets/Images/home-solana.png'),
    ethereum: require('@/Assets/Images/ethereum.png'),
    ethereumHome: require('@/Assets/Images/home-ethereum.png'),
    kucoinHome: require('@/Assets/Images/home-kucoin.png'),
    twitter: require('@/Assets/Images/twitter.png'),
    telegram: require('@/Assets/Images/telegram.png'),
    github: require('@/Assets/Images/github.png'),
    investigation: require('@/Assets/Images/investigation.png'),
    discord: require('@/Assets/Images/discord.png'),
    world: require('@/Assets/Images/world.png'),
    unicrypt: require('@/Assets/Images/unicrypt.png'),
    coinmarketcap: require('@/Assets/Images/coinmarketcap.png'),
    bscscan: require('@/Assets/Images/bscscan.png'),
    pancake: require('@/Assets/Images/pancake.png'),
    star: require('@/Assets/Images/star.png'),
    starFilled: require('@/Assets/Images/star_filled.png'),
    up: require('@/Assets/Images/up.png'),
    down: require('@/Assets/Images/down.png'),
    uniswap: require('@/Assets/Images/uniswap.png'),
    raydium: require('@/Assets/Images/raydium.png'),
    sushi: require('@/Assets/Images/sushi.png'),
    sushiswap: require('@/Assets/Images/sushiswap.png'),
    arrowUp: require('@/Assets/Images/arrow-up.png'),
    arrowDown: require('@/Assets/Images/arrow-down.png'),
    closeFilled: require('@/Assets/Images/close-filled.png'),
    comingSoon: require('@/Assets/Images/coming-soon.png'),
    addToFavorite: require('@/Assets/Images/add-to-favorite.png'),
  }
}
